## Matrix Algebrea

Date 19 Feb 25 \
Class 13

(Note Class 11 was line Bayesian Analysis and Chi-square theory; 12 was general advice on Lab malpractice)


#### Recap of basic matrix operations

In [1]:
import numpy as np
# define a matrix
A = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(A)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [2]:
# access rows
print(A[0]) # first row

[1 2 3]


In [3]:
# access elements
print(A[1, 2]) # element A12 -- Note first element is A00

6


In [4]:
print(A[1, 1:]) # print all element of second row from element number 2 and more

[5 6]


In [5]:
# access columns
print(A[:, 0]) # first column

[1 4 7]


In [6]:
# access the dimensions of the matrix
B = np.array([[1,2,3], [4,5,6]]) # define 2*3 matrix
print(B.shape, 'B - dimensions')

(2, 3) B - dimensions


In [7]:
print(A.shape)

(3, 3)


In [8]:
print(B.shape[1], '--- number of columns')
print(B.shape[0], '--- number of rows')

3 --- number of columns
2 --- number of rows


In [9]:
# using shape to get all columns
for i in range(A.shape[1]):
    print(A[:, i], ' --> column no.', i)


[1 4 7]  --> column no. 0
[2 5 8]  --> column no. 1
[3 6 9]  --> column no. 2


In [10]:
# define a matrix (say 3*4) with all elements zero
C = np.zeros((3, 4))
print(C)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


#### Code for matrix multiplications 

In [11]:
# define two matrics
A = np.array([[1, 2], [2, 1]])
B = np.array([[2, 3], [3, 4]])

In [12]:
print('A \n', A)
print('B \n', B)
print('A*B \n', np.matmul(A, B))

A 
 [[1 2]
 [2 1]]
B 
 [[2 3]
 [3 4]]
A*B 
 [[ 8 11]
 [ 7 10]]


In [13]:
# write a function to perform matrix multiplication

def matrix_multiplication(A, B):
    """
    parameters:
    A: matrix
    B: matrix

    Returns: A*B
    """

    # define the shape of A*B
    A_shape = A.shape
    B_shape = B.shape

    # check if we can perform A*B operation
    if A.shape[1] is not B.shape[0]:
        print('Can not multiply matrices with shapes', A_shape, B_shape)
        return

    # define a zero matrix
    C = np.zeros((A.shape[0], B.shape[1]))

    # perform A*B
    for i in range(A.shape[0]):
        for j in range(B.shape[1]):
            C[i, j] = np.sum(A[i, :]*B[:, j])

    return C
    


In [14]:
P = np.array([1, 2])
Q = np.array([2, 3])
print(np.sum(P*Q))

8


In [15]:
matrix_multiplication(A, B)

array([[ 8., 11.],
       [ 7., 10.]])

In [16]:
C = np.array([[1,2,3], [4,5,6], [7,8,9]])
matrix_multiplication(A, C)

Can not multiply matrices with shapes (2, 2) (3, 3)


#### get a random interger matrix

In [17]:
np.random.randint?

Docstring:
randint(low, high=None, size=None, dtype=int)

Return random integers from `low` (inclusive) to `high` (exclusive).

Return random integers from the "discrete uniform" distribution of
the specified dtype in the "half-open" interval [`low`, `high`). If
`high` is None (the default), then results are from [0, `low`).

.. note::
    New code should use the `~numpy.random.Generator.integers`
    method of a `~numpy.random.Generator` instance instead;
    please see the :ref:`random-quick-start`.

Parameters
----------
low : int or array-like of ints
    Lowest (signed) integers to be drawn from the distribution (unless
    ``high=None``, in which case this parameter is one above the
    *highest* such integer).
high : int or array-like of ints, optional
    If provided, one above the largest (signed) integer to be drawn
    from the distribution (see above for behavior if ``high=None``).
    If array-like, must contain integer values
size : int or tuple of ints, optional
    Outp

In [18]:
P = np.random.randint(low=0, high=10, size=(3, 4))
print(P)

[[3 3 5 2]
 [3 2 2 9]
 [0 0 4 0]]


In [19]:
Q = np.random.randint(low=0, high=10, size=(4, 5))
print(Q)

[[4 2 4 8 3]
 [4 4 4 2 0]
 [5 8 9 4 8]
 [5 5 2 9 0]]


In [20]:
PQ = matrix_multiplication(P, Q)
print(PQ)

[[ 59.  68.  73.  68.  49.]
 [ 75.  75.  56. 117.  25.]
 [ 20.  32.  36.  16.  32.]]


In [21]:
print(np.matmul(P, Q))

[[ 59  68  73  68  49]
 [ 75  75  56 117  25]
 [ 20  32  36  16  32]]


In [22]:
print(P@Q)

[[ 59  68  73  68  49]
 [ 75  75  56 117  25]
 [ 20  32  36  16  32]]
